title: Debargha Saha
email: debarghasaha01@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sometimes all you need is dedication and commitment to your work, and see the magic happen!!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: saha_debargha
github_username:  Stark-developer01

author:
    name: Debargha Saha
    email: debarghasaha01@gmail.com
social:
  github: Stark-developer01
  twitter: saha_debargha
  facebook: debargha01
  linkedin: debargha-saha-572260168
  instagram: saha_debargha

  defaults:
    -
      scope:
        path: ""
        type: "posts"
      values:
        layout: "post"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
port: 8080
timezone: Asia/Kolkata

# Exclude from processing.
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    -  Readme.md
    -  favicon.ico
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
